### PR TITLE
Fix errors

### PR DESCRIPTION
**Pull request by Travja**
There were just a few errors that caused things to break on occasion. This should fix them ;)

### CODE REVIEW

**Comment by guipenedo** [comment]
Thank you for this. Could you specify which issues changing the listener priority fixes?

**Comment by Travja** [comment]
I split up the bridge permission check with the set permission and changed
the priority because it had been causing a ConcurrentModificationException.
That allows it to set the permission in a safe way before other permission
checks are run.

**Comment by AaronMcHale** [comment]
Would like to see this merged as Maven support would be useful

**Comment by guipenedo** [comment]
Merged. Thanks a lot!

**Pull request merged**
